"""add_domain_models

Revision ID: 00be73cfb713
Revises: 
Create Date: 2026-02-24 18:00:11.391860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00be73cfb713'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем расширение pgcrypto для gen_random_uuid()
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index('ix_tenants_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_tenants_slug', ['slug'], unique=False)

    op.create_table('bank_accounts',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Название счёта (например, 'Основный счёт')"),
    sa.Column('account_number', sa.String(length=20), nullable=False, comment='Номер счёта (20 цифр)'),
    sa.Column('bank_name', sa.String(length=255), nullable=False, comment='Название банка'),
    sa.Column('bank_bik', sa.String(length=9), nullable=False, comment='БИК банка'),
    sa.Column('bank_correspondent_account', sa.String(length=20), nullable=True, comment='Корреспондентский счёт банка'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Валюта счёта (ISO 4217)'),
    sa.Column('balance', sa.Numeric(precision=19, scale=4), nullable=True, comment='Текущий баланс'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли счёт'),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_bank_accounts_account_number', ['account_number'], unique=False)
        batch_op.create_index('ix_bank_accounts_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_bank_accounts_tenant_account', ['tenant_id', 'account_number'], unique=True)
        batch_op.create_index('ix_bank_accounts_tenant_id', ['tenant_id'], unique=False)

    op.create_table('roles',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Системные роли нельзя удалять/редактировать'),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('ix_roles_code', ['code'], unique=False)
        batch_op.create_index('ix_roles_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_roles_tenant_code_unique', ['tenant_id', 'code'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.create_index('ix_users_tenant_email_unique', ['tenant_id', 'email'], unique=True)
        batch_op.create_index('ix_users_tenant_id', ['tenant_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True, comment='ID пользователя (nullable для системных событий)'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Тип события: 'user.login', 'document.create', etc."),
    sa.Column('event_category', sa.String(length=50), nullable=False, comment="Категория: 'auth', 'app', 'system', 'security'"),
    sa.Column('action', sa.String(length=50), nullable=False, comment="Действие: 'create', 'update', 'delete', 'login', 'logout'"),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Статус: 'success' или 'failure'"),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP-адрес (IPv4/IPv6)'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent'),
    sa.Column('related_type', sa.String(length=50), nullable=True, comment="Тип объекта: 'User', 'Transaction', 'Document', etc."),
    sa.Column('related_id', sa.String(length=64), nullable=True, comment='ID объекта'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Детали события (старые/новые значения)'),
    sa.Column('message', sa.Text(), nullable=True, comment='Человекочитаемое описание'),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_event_category', ['event_category'], unique=False)
        batch_op.create_index('ix_audit_logs_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_audit_logs_tenant_category_date', ['tenant_id', 'event_category', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)

    op.create_table('cash_operations',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=False, comment="Тип: 'income' (ПКО) или 'expense' (РКО)"),
    sa.Column('document_number', sa.String(length=50), nullable=False, comment='Номер ордера'),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=False, comment='Дата ордера'),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False, comment='Сумма операции'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True, comment='ФИО или название контрагента'),
    sa.Column('counterparty_inn', sa.String(length=12), nullable=True, comment='ИНН контрагента'),
    sa.Column('description', sa.Text(), nullable=True, comment='Основание операции'),
    sa.Column('bank_account_id', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='Проведена ли операция'),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_operations', schema=None) as batch_op:
        batch_op.create_index('ix_cash_operations_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_cash_operations_document_date', ['document_date'], unique=False)
        batch_op.create_index('ix_cash_operations_tenant_date', ['tenant_id', 'document_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_operations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_cash_operations_tenant_number', ['tenant_id', 'document_number'], unique=True)

    op.create_table('memberships',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False, comment='Владелец tenant (максимальные права)'),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_memberships_tenant_user')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('ix_memberships_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_memberships_role_id', ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_memberships_user_id', ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment="Тип: 'info', 'warning', 'error', 'success'"),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True, comment="Тип связанного объекта: 'transaction', 'document', etc."),
    sa.Column('related_id', sa.String(length=64), nullable=True, comment='ID связанного объекта'),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notifications_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_notifications_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_unread', ['user_id', 'is_read'], unique=False)

    op.create_table('transactions',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('bank_account_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False, comment="Тип: 'incoming' или 'outgoing'"),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False, comment='Сумма транзакции'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Валюта (ISO 4217)'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, comment='Дата проведения транзакции'),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True, comment='Название контрагента'),
    sa.Column('counterparty_inn', sa.String(length=12), nullable=True, comment='ИНН контрагента'),
    sa.Column('counterparty_account', sa.String(length=20), nullable=True, comment='Счёт контрагента'),
    sa.Column('description', sa.Text(), nullable=True, comment='Назначение платежа'),
    sa.Column('document_number', sa.String(length=50), nullable=True, comment='Номер документа'),
    sa.Column('fingerprint', sa.String(length=64), nullable=True, comment='Хэш для дедупликации'),
    sa.Column('external_id', sa.String(length=100), nullable=True, comment='Внешний ID транзакции'),
    sa.Column('is_processed', sa.Boolean(), nullable=False, comment='Обработана ли транзакция'),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index('ix_transactions_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_transactions_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('ix_transactions_tenant_fingerprint', ['tenant_id', 'fingerprint'], unique=True)
        batch_op.create_index('ix_transactions_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('ix_transactions_tenant_occurred', ['tenant_id', 'occurred_at'], unique=False)

    op.create_table('edo_documents',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment="Тип: 'invoice', 'act', 'waybill', 'upd', etc."),
    sa.Column('document_number', sa.String(length=100), nullable=False, comment='Номер документа'),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=False, comment='Дата документа'),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=True, comment='Сумма документа'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True, comment='Название контрагента'),
    sa.Column('counterparty_inn', sa.String(length=12), nullable=True, comment='ИНН контрагента'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус: draft, sent, signed, rejected, cancelled'),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('bank_account_id', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edo_documents', schema=None) as batch_op:
        batch_op.create_index('ix_edo_documents_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_edo_documents_document_date', ['document_date'], unique=False)
        batch_op.create_index('ix_edo_documents_status', ['status'], unique=False)
        batch_op.create_index('ix_edo_documents_tenant_date', ['tenant_id', 'document_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_edo_documents_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_edo_documents_tenant_number', ['tenant_id', 'document_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edo_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_edo_documents_tenant_number')
        batch_op.drop_index(batch_op.f('ix_edo_documents_tenant_id'))
        batch_op.drop_index('ix_edo_documents_tenant_date')
        batch_op.drop_index('ix_edo_documents_status')
        batch_op.drop_index('ix_edo_documents_document_date')
        batch_op.drop_index('ix_edo_documents_deleted_at')

    op.drop_table('edo_documents')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_tenant_occurred')
        batch_op.drop_index('ix_transactions_tenant_id')
        batch_op.drop_index('ix_transactions_tenant_fingerprint')
        batch_op.drop_index('ix_transactions_occurred_at')
        batch_op.drop_index(batch_op.f('ix_transactions_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_transactions_external_id'))
        batch_op.drop_index('ix_transactions_deleted_at')
        batch_op.drop_index(batch_op.f('ix_transactions_bank_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_unread')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notifications_tenant_id')
        batch_op.drop_index('ix_notifications_deleted_at')
        batch_op.drop_index('ix_notifications_created_at')

    op.drop_table('notifications')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_memberships_user_id')
        batch_op.drop_index(batch_op.f('ix_memberships_tenant_id'))
        batch_op.drop_index('ix_memberships_role_id')
        batch_op.drop_index('ix_memberships_deleted_at')

    op.drop_table('memberships')
    with op.batch_alter_table('cash_operations', schema=None) as batch_op:
        batch_op.drop_index('ix_cash_operations_tenant_number')
        batch_op.drop_index(batch_op.f('ix_cash_operations_tenant_id'))
        batch_op.drop_index('ix_cash_operations_tenant_date')
        batch_op.drop_index('ix_cash_operations_document_date')
        batch_op.drop_index('ix_cash_operations_deleted_at')

    op.drop_table('cash_operations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index('ix_audit_logs_tenant_category_date')
        batch_op.drop_index('ix_audit_logs_event_type')
        batch_op.drop_index('ix_audit_logs_event_category')
        batch_op.drop_index('ix_audit_logs_created_at')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_tenant_id')
        batch_op.drop_index('ix_users_tenant_email_unique')
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_deleted_at')

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_tenant_id'))
        batch_op.drop_index('ix_roles_tenant_code_unique')
        batch_op.drop_index('ix_roles_deleted_at')
        batch_op.drop_index('ix_roles_code')

    op.drop_table('roles')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_bank_accounts_tenant_id')
        batch_op.drop_index('ix_bank_accounts_tenant_account')
        batch_op.drop_index('ix_bank_accounts_deleted_at')
        batch_op.drop_index('ix_bank_accounts_account_number')

    op.drop_table('bank_accounts')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('ix_tenants_slug')
        batch_op.drop_index('ix_tenants_deleted_at')

    op.drop_table('tenants')
    # ### end Alembic commands ###
    
    # Удаляем расширение pgcrypto
    op.execute('DROP EXTENSION IF EXISTS pgcrypto')
