"""add_sbwebhook_events

Revision ID: c4dd3f4dfa15
Revises: 00be73cfb713
Create Date: 2026-02-25 09:40:45.023597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4dd3f4dfa15'
down_revision: Union[str, None] = '00be73cfb713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sbis_webhook_events',
    sa.Column('tenant_id', sa.String(), nullable=True, comment='ID tenant (nullable для глобальных событий)'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Тип события СБИС'),
    sa.Column('event_id', sa.String(length=100), nullable=False, comment='Уникальный ID события от СБИС'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Полные данные события'),
    sa.Column('signature', sa.String(length=255), nullable=True, comment='Подпись вебхука для верификации'),
    sa.Column('processed', sa.Boolean(), nullable=False, comment='Обработано ли событие'),
    sa.Column('processing_error', sa.Text(), nullable=True, comment='Ошибка обработки'),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sbis_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sbis_webhook_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sbis_webhook_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_sbwh_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_sbwh_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_sbwh_processed', ['processed'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('ix_tenants_slug')
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))
        batch_op.create_index('ix_tenants_slug', ['slug'], unique=False)

    with op.batch_alter_table('sbis_webhook_events', schema=None) as batch_op:
        batch_op.drop_index('ix_sbwh_processed')
        batch_op.drop_index('ix_sbwh_event_type')
        batch_op.drop_index('ix_sbwh_created_at')
        batch_op.drop_index(batch_op.f('ix_sbis_webhook_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sbis_webhook_events_event_id'))

    op.drop_table('sbis_webhook_events')
    # ### end Alembic commands ###
